### ISSUE TITLE
missing http-parser/http_parser.h

### ISSUE THREAD

**Issue by grooverdan** [vincentbernat/rfc5077#1]
Hey,

Thanks for the great bit of code and blog article. I've learned a lot and I though I almost had a good grasp on session ticket and I hadn't even looked at session identifiers yet.

I'm in the middle of writing a proper implementation of rfc5077 tickets for nginx and was looking at your code base for testing.

Noticed that http-parser/http_parser.h is missing from the repository. Do you have it around?

I'll probably add a bit of build documentation here once I've done.

Thanks again. Good to see the weeks of standards development translate into implementations.

**Comment by DarcyNing** [comment]
would you mind please teach me how to install...

**Comment by grooverdan** [comment]
@DarcyNing - you can follow the instructions https://github.com/vincentbernat/rfc5077#getting-started

Also see the "clone or download" button.
