### ISSUE TITLE
make problems

### ISSUE THREAD

**Issue by DarcyNing** [vincentbernat/rfc5077#10]
When I  have tried  to install this software, a problem accurs....

cc -o rfc5077-client rfc5077-client.o common.o  -lssl -lcrypto  
rfc5077-client.o: In function `resultinfo_display':
/usr/local/src/rfc5077/rfc5077-client.c:131: undefined reference to `SSL_SESSION_get0_cipher'
/usr/local/src/rfc5077/rfc5077-client.c:153: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:160: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:169: undefined reference to `SSL_SESSION_has_ticket'
rfc5077-client.o: In function `resultinfo_write':
/usr/local/src/rfc5077/rfc5077-client.c:204: undefined reference to `SSL_SESSION_get0_cipher'
/usr/local/src/rfc5077/rfc5077-client.c:216: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:219: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:223: undefined reference to `SSL_SESSION_has_ticket'
rfc5077-client.o: In function `tests':
/usr/local/src/rfc5077/rfc5077-client.c:278: undefined reference to `SSL_set_options'
/usr/local/src/rfc5077/rfc5077-client.c:297: undefined reference to `SSL_session_reused'
rfc5077-client.o: In function `main':
/usr/local/src/rfc5077/rfc5077-client.c:378: undefined reference to `OPENSSL_init_ssl'
/usr/local/src/rfc5077/rfc5077-client.c:379: undefined reference to `OPENSSL_init_ssl'
/usr/local/src/rfc5077/rfc5077-client.c:380: undefined reference to `TLS_client_method'
collect2: ld returned 1 exit status
make: *** [rfc5077-client] Error 1

**Comment by vincentbernat** [comment]
You need to `git checkout 3c37c33b46e0` if you don't have OpenSSL 1.1+.

**Comment by DarcyNing** [comment]
would you teach me how, please

**Comment by DarcyNing** [comment]
I hava openssl 1.1.0e installed already.

[root@www rfc5077]# openssl version -a
OpenSSL 1.1.0e  16 Feb 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
compiler: gcc -DZLIB -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_PIC -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/openssl/ssl\"" -DENGINESDIR="\"/usr/local/openssl/lib/engines-1.1\""  -Wa,--noexecstack
OPENSSLDIR: "/usr/local/openssl/ssl"
ENGINESDIR: "/usr/local/openssl/lib/engines-1.1"

**Comment by DarcyNing** [comment]
please.......

**Comment by DarcyNing** [comment]
cc -g -Werror -Wall -ansi -std=c99 -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE   -c -o rfc5077-client.o rfc5077-client.c
cc -g -Werror -Wall -ansi -std=c99 -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE   -c -o common.o common.c
cc -o rfc5077-client rfc5077-client.o common.o  -lssl -lcrypto  
cc -g -Werror -Wall -ansi -std=c99 -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE -I/usr/include/libev   -c -o rfc5077-server.o rfc5077-server.c
make -C http-parser package
make[1]: Entering directory `/usr/local/src/rfc5077/http-parser'
ar rcs libhttp_parser.a http_parser.o
make[1]: Leaving directory `/usr/local/src/rfc5077/http-parser'
cc -o rfc5077-server rfc5077-server.o common.o http-parser/libhttp_parser.a  -lev -lssl -lcrypto  
cc -g -Werror -Wall -ansi -std=c99 -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE   -c -o rfc5077-pcap.o rfc5077-pcap.c
cc -o rfc5077-pcap rfc5077-pcap.o common.o  -lpcap
cc -g -Werror -Wall -ansi -std=c99 -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE   -c -o openssl-client.o openssl-client.c
cc -g -Werror -Wall -ansi -std=c99 -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE   -c -o common-client.o common-client.c
cc -o openssl-client openssl-client.o common-client.o common.o  -lssl -lcrypto  
cc -g -Werror -Wall -ansi -std=c99 -D_POSIX_SOURCE -D_BSD_SOURCE -D_GNU_SOURCE   -c -o gnutls-client.o gnutls-client.c
cc1: warnings being treated as errors
gnutls-client.c: in fucnction ‘connect_ssl’:
gnutls-client.c:97:Error: implicit declaration function ‘gnutls_session_ticket_enable_client’
make: *** [gnutls-client.o] error 1
